### ISSUE TITLE
Problem with requesting all customer details

### ISSUE THREAD

**Issue by ewanmceachran** [dezrez/DezrezCoreAPI#13]
I'm trying to get the details for all customers, on the UAT system, which I'm assuming I need to do via:

/api/globalsearch/people

When I authenticate requesting the scope 'people_basic_read', calls to the above method fail with '401:Unauthorised'. So I'm guessing that I instead need the scope 'people_read'. But when I try to authenticate requesting the 'people_read' scope, I get a '400:Bad Request' response. I don't know if this indicates that that scope is unavailable to me, or if something other is going wrong.

**Comment by dendle** [comment]
Hello Ewan,

Yes, I'm afraid I forgot to mention which scopes were currently enabled and which were not.

Let me have a look at the scopes, and make suggestions on the best way to get all contact details.

I'll get back to you ASAP.

Cheers,
Matt

**Comment by ewanmceachran** [comment]
Thanks Matt - any ETA on the ASAP?

**Comment by dendle** [comment]
Hello Ewan - Sorry about the delay, had some issues to deal with after I wrote that post, and forgot to come back to it!

I've granted you the extra scope:

people_read

Try and get using this scope - it should work.

I'm looking at making things easier for you by using a LastUpdated date - this would allow you to access the search facilities and only get items that are new.

I think this wouldnt be too much work, so let me know if you think you need it.

Cheers,
Matt

**Comment by ewanmceachran** [comment]
Thanks - I am now able to run a search via globalsearch/people. However, I don't think that it's going to be fit for my purpose - I was hoping that by passing in an empty search term it might return all people, but in fact it seems that the search term is mandatory (despite the documentation not marking it as such).  In extremis I could do something horrible like running searches for 'a' through 'z' and amalgamating the results, but obviously I'd rather not. But I can't see an alternative approach. Could you advise?

Having a LastUpdated date would be great, of course, for whatever the right approach is.

**Comment by marc-harry** [comment]
Hi @ewanmceachran,

To give you an update on this, we have pushed an update to the UAT environment which has last updated available on the returned results and also the endpoints on api/globalsearch have a lastUpdated parameter so you can get all results where the last updated is greater than the date passed in.

With the issue you mentioned of the search term being mandatory, it is mandatory however if you need to get all result's you can pass the wildcard \* to the term like so: `?term=*`

I hope this information helps.

Cheers,
Marc

**Comment by ewanmceachran** [comment]
Thanks for this - this will be very helpful.

My next question: should I be able to make calls to /api/people/{id} ? I'm trying to make calls to this using an IDs I've got from the search, and am getting 500 errors. (I am appending the agencyId value on the query string).

Thanks. Ewan

**Comment by ewanmceachran** [comment]
I also don't seem to be able to get property data. Is that because I don't have property_read? Could I just have full permissions within the scope of the agency, because I'm getting really confused about what the different error messages I'm getting mean. 

For example, I don't seem to be able to get Agency information. You have an API call that's specified thus:

GET /api/Agency

with the description: 'Gets an agency by its id'.

But, slightly bafflingly, there is no id parameter specified in the documentation. I've tried appending ?agencyID={my id} to the querystring, but that gives me a 500 error. I don't know if that's a security error, a syntax error, a bug, or what.

**Comment by dendle** [comment]
Hello Ewan,

With regards to the first part of your question, yes, that call should work for you - We'll have a look and find out why you got that error.

As for the second part, the confusion is probably down to the way we are integrating - we are granting you access to make calls on (eventually) several different agencies.  We need to know in which agency context you are calling the API in order to return the right information.  Normally, API callers are logged in as the current user, which is only associated to a single agency, and these types of calls dont need to specify an agencyID as we already know which agency they are with, as they are logged in.

Couple with the fact that our documentation isn't quite up to date, or still left at its default in some cases, it's no wonder that its gotten you confused!

The GET /api/Agency call should be working for you, as long as you supply an AgencyID in the URL parameter - what parameter value did you supply?

Cheers,
Matt

**Comment by dendle** [comment]
Also, if you have any errors, I can look them up for you if you give me the error reference GUID that you get - I can find the issues much quicker this way.

Thanks again,
Matt

**Comment by ewanmceachran** [comment]
Hi Matt,

Thanks a lot for your help so far. On the various things:
1. Permissions

I'm using the list of scopes specified in "DEZREZ CORE API OVERVIEW", and testing gives me the following results:

property_read - No
property_write - No
people_read - Yes
people_basic_read - Yes
people_write - No
event_read - No
event_write - No
property_basic_read - Yes
impersonate_user - No
document_read - No
document_write - No
lead_sender - No
impersonate_web_user - No
impersonate_any_agency - No

Since I'm not clear exactly what data we're going to be requesting- the scope of the project is a little unclear to me - and the API documentation doesn't list the required scopes per call, would it be possible to turn on all of the 'read' permissions for me?
1. Requesting 'people' data.

I can get people data via the globalsearch call, but the results I've got don't have any 'Address' data. I was trying to use the 'people' call to see if address data is included in there, but I can't make it work. I'm using the 'Id' field I'm getting back via globalsearch. An example:

https://core-api-uat.dezrez.com/api/people/2735957?agencyID=125

{"Message":"An error has occurred. If this persists please contact us","ErrorReference":"258b9eeb-9e27-4f67-9544-c5af4422c5e6","Details":"Error occured whilst invoking action Get on controller PeopleController. This error has been logged.","ValidationErrors":null}
1. Requesting 'agency' data

I'm not sure if I'll need this: I thought it might be the case that if I find the branches per agency then I could work down a branch hierarchy. However:

https://core-api-uat.dezrez.com/api/Agency?agencyID=125

{"Message":"An error has occurred. If this persists please contact us","ErrorReference":"83e48823-20cc-4f31-94c0-1c1ba529f7e3","Details":"Error occured whilst invoking action Get on controller AgencyController. This error has been logged.","ValidationErrors":null}

Thanks, Ewan

**Comment by ewanmceachran** [comment]
Hi - I now have more permissions, but I'm still getting the errors of the kind shown above. Any ideas?

**Comment by marc-harry** [comment]
Hi @ewanmceachran,

Apologies for the delay in getting back to you, I have had a look further look into the issue you were having and the issues should now be resolved however there is just one additional scope you need to pass and that is the "impersonate_web_user", this scope has now been provisioned for you. I gave this a go in the test client you sent use and it was all working as expected. So just to confirm with you the full list of scopes you will be passing are: impersonate_web_user, people_read, people_basic_read, property_basic_read, property_read and event_read.

I hope this helps.

Cheers,
Marc

**Comment by ewanmceachran** [comment]
Thanks for this, it has certainly opened up some parts of the API that I wasn't able to see. I've had a play with it today, and have some further points / questions. Let me just address properties for now.

I am still getting authentication errors on the following calls, which seems odd given that I have both property_basic_read and property_read

https://core-api-uat.dezrez.com/api/globalsearch/properties
https://core-api-uat.dezrez.com/api/property/{id}

I can get data back from 

https://core-api-uat.dezrez.com/api/simplepropertyrole/search?

But I don't understand what this data is, and there's not much of it.

More promisingly, though, I'm getting 11439 pieces of data back from

https://core-api-uat.dezrez.com/api/list/property

Looking at the RoleType and RoleStatus values on these objects, there are some 'Selling' and some 'Letting' roles, with what appears to be pipeline status values. I'm guessing that I can use this call to pull out current properties for sale and current properties that have / are trying to find tenants. Does this seem like the right thing to do?

Thanks, Ewan

**Comment by ewanmceachran** [comment]
Hello again,

I'm now looking at the RoleType and RoleStatus values on the Groups that individuals belong to. Is there any documentation on the possible values of these and their semantics? I'm trying to use these to distinguish between people looking to buy, people looking for lets, sellers, landlords, tenants, etc. But without documentation there's a lot of guesswork involved. (Plus, of course, there might be a better way of approaching this...)

Any help much appreciated.

**Comment by rjmacarthy** [comment]
@ewanmceachran in regards to your last comment, these are system Enums which you can query via the API.  For example:

GET: api/enum?typeName=RoleType

GET: api/enum?typeName=RoleStatus

These calls will bring you back all the possible values which can be assigned to the group role status and group role type.  If you see anything with a systemName, Name, and Id it's likely to be an enum type that you can query via the API.

Hope that helps.

Richard.

**Comment by ewanmceachran** [comment]
Thanks for the feedback. I guess that what would be really useful (especially given the abstract Role system that you guys employ) would be documentation which said, for each possible triple:

ObjectType - RoleType - RoleStatus - What this actually means 

I note that in the enums there are RoleStatuses of 'Let', 'Pre Tenancy', 'Post Tenancy' etc., which I've not actually seen anywhere. Do these belong to properties? If so, the reason that I haven't seen them might be that I'm still getting Unauthorized responses when I try to request /property/{id} or /globalsearch/properties.

Thanks, Ewan

**Comment by marc-harry** [comment]
Hi @ewanmceachran,

I have pushed an update to the UAT environment which resolves the errors you were seeing before. It was again down to permissions but that's sorted now.

In answer to your other questions the endpoint api/simplepropertyrole/search? is suppose to return a light datacontract and is designed for things such as web feeds. It should be returning properties that are on the market both sales and lettings depending on parameters passed to it.

The following endpoint:
[https://core-api-uat.dezrez.com/api/list/property](https://core-api-uat.dezrez.com/api/list/property)

Also returns properties on the market but it can also return properties that are in a valued state or those that have been withdrawn or even completed. So the difference really is the simplepropertyrole only gets active roles for properties being marketed whereas list/property can get you roles for properties in any part of the marketing cycle. And like @rjmacarthy stated using the enum endpoints to get all possible RoleTypes and RoleStatus will then allow you to figure out which are in certain states. Or to even pass a filter to the list/property endpoint to only get back roles of certain RoleTypes or RoleStatuses.

I hope this information and if you have any questions let me know.

Cheers,
Marc

**Comment by ewanmceachran** [comment]
Thanks for the update. very useful..

The thing that's currently perplexing me is tenants. Does the system contain data about tenants? If so, what data indicates that a person is a tenant? Could you point me to an example of someone who is a tenant?

Cheers, Ewan

**Comment by marc-harry** [comment]
Hi @ewanmceachran,

Currently we hold information about tenants but we currently don't have any way to request to get all people who are tenants of all the marketing properties. But you can query to get all people who are looking to become/are tenants but you won't be able to tell for this if they are currently a tenant. The endpoint for this is:
[https://core-api-uat.dezrez.com/api/list/groupinterests](https://core-api-uat.dezrez.com/api/list/groupinterests)

That endpoint takes a filter which if you set the interest flags property of the filter to contain 'LettingsApplicant' that will get you all tenants and people looking to become tenants.

Is this what you were looking for or was it more of a way to list all people in active tenancies?

Cheers,
Marc

**Comment by ewanmceachran** [comment]
Hi Marc,

The spec that I'm working towards - which gives the 'ideal' set of data for an integration - contains a boolean property of a client 'IsTenant', and also an object property 'Tenancies'. But if you're saying that we cannot in principle extract data to support those properties then I'll skip them.

Thanks, Ewan

**Comment by dendle** [comment]
Hi Ewan, just to give some context, the reason for the lack of tenancy info is simply due to that module not being wholly complete yet inside Rezi.

Once complete, the tenant info will be available to you.

What you can take from this is that the people using Rezi at this moment will not be overly concerned with recording or using tenant info. If they were, they wouldn’t be using Rezi today.

Regards
Chris.

---

Christopher Bennett
Head of Development | Enhance Portfolio Manager

[cid:image001.png@01D1F3AE.2630DA90]

Ethos, Kings Road, Swansea, SA1 8AS
Web: enhance.dezrez.comhttp://enhance.dezrez.com/ | www.dezrez.comhttp://www.dezrez.com/ | Tel: +44 0845 465 22 22 | Email: christopher.bennett@dezrez.commailto:christopher.bennett@dezrez.com

[Follow dezrezsupport on Twitter]http://www.twitter.com/dezrezsupport[Like us on Facebook]http://www.facebook.com/dezrezsoftware/[Connect with us on Linkedin]http://www.linkedin.com/company/dezrez[Subscribe to us on Youtube]http://www.youtube.com/user/DezrezSoftware

[http://www.dezrez.com/drapp/estateagents/127/signature/FastGrowth50.png]
[http://www.dezrez.com/drapp/estateagents/127/signature/awards.jpg]

All information included within this message, including attachments is of a confidential nature, possibly exempt from disclosure under applicable law, and intended only for named recipients. If you are not a named recipient; access, reading, copying, disclosure or re-use of information is strictly prohibited, and possibly unlawful.

If you have received this message in error, please immediately delete this message from your system, and contact Dezrez Services Limited offices on +44 0845 465 22 22. Any views or opinions expressed in this message, are solely those of the author, and do not necessarily represent the views of the company.

**Comment by marc-harry** [comment]
Hi @ewanmceachran,

If this is on an page that shows an individual client then this is possible. If you request the group for the client: [https://core-api-uat.dezrez.com/api/group/{id}](https://core-api-uat.dezrez.com/api/group/{id})

In the response data contract there is a list property called roles. In that list there should be a role which has RoleType = Tenant and RoleStatus = Active, would indicate IsTenant and to get further information about the tenancy you could use the Id for that Tenant Role and request full details from [https://core-api-uat.dezrez.com/api/role/{id}](https://core-api-uat.dezrez.com/api/role/{id})

Cheers,
Marc

**Comment by ewanmceachran** [comment]
Yes, I saw that on the possible values of RoleType there is Tenant. But as part of my testing I enumerated all the pairs of RoleType / RoleStatus on the groups that I could find, and Tenant didn't appear (either because of the module not being wholly complete or because I managed to grab only a subset of the group IDs available to me). In any case, I'm happy to leave it pro tem.

Incidentally, since you referenced the API call above, I can make calls like this:

https://core-api-uat.dezrez.com/api/role/4687198/offers?agencyID=125

but the following gives me an authentication error:

https://core-api-uat.dezrez.com/api/role/4687198?agencyID=125

**Comment by ewanmceachran** [comment]
Authorisation error, rather

**Comment by marc-harry** [comment]
Hi @ewanmceachran,

The authorisation error you were getting for the role endpoint shouldn't occur any more following a fix just pushed to the UAT environment. I've tested it our side and that call you linked worked.

Cheers,
Marc

**Comment by ewanmceachran** [comment]
Hi,

Should I be expecting the UAT environment to have orphaned records? For example, I do a search for viewing events passing in the filter:

{
    "EventTypes": 
    [{
        "SystemName": "Viewing"
    }],
    "GroupId": 2381402
}

This returns me a single record in which a Mr Eldridge views a property in Rugeley Road. The Id of Mr Eldridge's 'viewing group' is 2381402. However, when I try to request details of this group either by /api/group/{id} or /api/globalsearch/groups there is no corresponding record.

Thanks, Ewan

**Comment by ewanmceachran** [comment]
Hi again,

I'm confused about the data coming back from a call such as:

**Comment by ewanmceachran** [comment]
Sorry, bit of a premature posting there...

I'm confused about the data coming back from a call such as

/api/role/4688240/offers?agencyID=125

The first item in the collection is of response type 'Accepted'. It contains two objects: ApplicantGroup and VendorGroup, which you'd think would correspond, respectively, to the folks making the offer and the folks selling the property. However, each object in this case is the _same_ group (Mrs Payne and Mr Rooke). Which I find peculiar. Now, it is possible to pull out what I take to be the actual vendor using the call

/api/role/4688240/vendors?agencyID=125

But I don't understand the results of the initial call. Is this just a bug, or am I missing something?

Thanks, Ewan

**Comment by rjmacarthy** [comment]
Hi @ewanmceachran I have closed this issue, and moved the new issues into separate ones.  It will be easier to track your questions this way. We will be looking into your questions today.

Thanks.

Richard.

Cannot retrieve full details of a group returned by a filter search. #15

Duplicate group applicant/vendor appearing when requesting offer details. #16
